name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Deploy target
        options: 
        - dev1
        - dev2
        - prod
      message:
        required: true
        default: "Write some messsage here"
      dryrun:
        type: boolean
        description: Dryrun or execute
      environment:
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environemt }}

    steps:
    - name: Log deploy target info (use github context)
      run: |
        echo "target: ${{ github.event.inputs.target }}"
        echo "message: ${{ github.event.inputs.message }}"
        echo "dryrun: ${{ github.event.inputs.dryrun }}"
    - name: Log deploy target info (use environment variables)
      run: |
        echo "target: $INPUT_TARGET"
        echo "message: $INPUT_MESSAGE"
        echo "dryrun: $INPUT_DRYRUN"
    - name: Deploy (use environemt secrets)
      run: |
        echo "Deploy target server: ${{ github.secrets.ENV_SERVER }}
